package com.vipulasri.jetinstagram.network

import com.google.gson.annotations.SerializedName

// WebRTC Signaling Response
data class WebRTCSignalingResponse(
    @SerializedName("sessionId") val sessionId: String?,
    @SerializedName("roomId") val roomId: String?,
    @SerializedName("peerId") val peerId: String?,
    @SerializedName("sessionType") val sessionType: String?,
    @SerializedName("sessionStatus") val sessionStatus: String?,
    @SerializedName("timestamp") val timestamp: Long?,
    @SerializedName("stunServers") val stunServers: List<String>?,
    @SerializedName("iceServers") val iceServers: String?,
    @SerializedName("rtcConfiguration") val rtcConfiguration: String?,
    @SerializedName("constraints") val constraints: String?,
    @SerializedName("localDescription") val localDescription: String?,
    @SerializedName("iceCandidates") val iceCandidates: List<String>?,
    @SerializedName("videoCodec") val videoCodec: String?,
    @SerializedName("audioCodec") val audioCodec: String?,
    @SerializedName("videoResolution") val videoResolution: String?,
    @SerializedName("videoFrameRate") val videoFrameRate: String?,
    @SerializedName("audioSampleRate") val audioSampleRate: String?,
    @SerializedName("audioChannels") val audioChannels: String?,
    @SerializedName("isEncrypted") val isEncrypted: Boolean?,
    @SerializedName("encryptionType") val encryptionType: String?,
    @SerializedName("networkType") val networkType: String?,
    @SerializedName("bandwidth") val bandwidth: String?,
    @SerializedName("latency") val latency: String?,
    @SerializedName("errorCode") val errorCode: String?,
    @SerializedName("errorMessage") val errorMessage: String?,
    @SerializedName("hasError") val hasError: Boolean?
)

// WebRTC Session Description Response
data class WebRTCSessionDescriptionResponse(
    @SerializedName("sessionId") val sessionId: String?,
    @SerializedName("type") val type: String?,
    @SerializedName("sdp") val sdp: String?,
    @SerializedName("sessionType") val sessionType: String?,
    @SerializedName("sessionStatus") val sessionStatus: String?,
    @SerializedName("timestamp") val timestamp: Long?,
    @SerializedName("videoCodec") val videoCodec: String?,
    @SerializedName("audioCodec") val audioCodec: String?,
    @SerializedName("videoResolution") val videoResolution: String?,
    @SerializedName("videoFrameRate") val videoFrameRate: String?,
    @SerializedName("audioSampleRate") val audioSampleRate: String?,
    @SerializedName("audioChannels") val audioChannels: String?,
    @SerializedName("videoBitrate") val videoBitrate: String?,
    @SerializedName("audioBitrate") val audioBitrate: String?,
    @SerializedName("videoQuality") val videoQuality: String?,
    @SerializedName("audioQuality") val audioQuality: String?,
    @SerializedName("networkType") val networkType: String?,
    @SerializedName("bandwidth") val bandwidth: String?,
    @SerializedName("latency") val latency: String?,
    @SerializedName("isEncrypted") val isEncrypted: Boolean?,
    @SerializedName("encryptionType") val encryptionType: String?,
    @SerializedName("iceServers") val iceServers: String?,
    @SerializedName("iceTransportPolicy") val iceTransportPolicy: String?,
    @SerializedName("bundlePolicy") val bundlePolicy: String?,
    @SerializedName("rtcpMuxPolicy") val rtcpMuxPolicy: String?,
    @SerializedName("videoConstraints") val videoConstraints: String?,
    @SerializedName("audioConstraints") val audioConstraints: String?
)

// WebRTC ICE Candidate Response
data class WebRTCIceCandidateResponse(
    @SerializedName("sessionId") val sessionId: String?,
    @SerializedName("candidate") val candidate: String?,
    @SerializedName("sdpMid") val sdpMid: String?,
    @SerializedName("sdpMLineIndex") val sdpMLineIndex: Int?,
    @SerializedName("usernameFragment") val usernameFragment: String?,
    @SerializedName("foundation") val foundation: String?,
    @SerializedName("component") val component: String?,
    @SerializedName("protocol") val protocol: String?,
    @SerializedName("priority") val priority: String?,
    @SerializedName("ip") val ip: String?,
    @SerializedName("port") val port: Int?,
    @SerializedName("type") val type: String?,
    @SerializedName("networkType") val networkType: String?,
    @SerializedName("networkCost") val networkCost: String?,
    @SerializedName("addressFamily") val addressFamily: String?,
    @SerializedName("bandwidth") val bandwidth: String?,
    @SerializedName("latency") val latency: String?,
    @SerializedName("packetLoss") val packetLoss: String?,
    @SerializedName("jitter") val jitter: String?,
    @SerializedName("isEncrypted") val isEncrypted: Boolean?,
    @SerializedName("encryptionType") val encryptionType: String?,
    @SerializedName("certificate") val certificate: String?,
    @SerializedName("timestamp") val timestamp: Long?,
    @SerializedName("errorCode") val errorCode: String?,
    @SerializedName("errorMessage") val errorMessage: String?,
    @SerializedName("hasError") val hasError: Boolean?
)

// WebRTC Session Description Request
data class WebRTCSessionDescriptionRequest(
    @SerializedName("sessionId") val sessionId: String,
    @SerializedName("type") val type: String,
    @SerializedName("sdp") val sdp: String,
    @SerializedName("sessionType") val sessionType: String = "video",
    @SerializedName("sessionStatus") val sessionStatus: String = "connecting",
    @SerializedName("videoCodec") val videoCodec: String = "H.264",
    @SerializedName("audioCodec") val audioCodec: String = "Opus",
    @SerializedName("videoResolution") val videoResolution: String = "1280x720",
    @SerializedName("videoFrameRate") val videoFrameRate: String = "30fps",
    @SerializedName("audioSampleRate") val audioSampleRate: String = "48kHz",
    @SerializedName("audioChannels") val audioChannels: String = "stereo",
    @SerializedName("videoBitrate") val videoBitrate: String = "1000",
    @SerializedName("audioBitrate") val audioBitrate: String = "64",
    @SerializedName("videoQuality") val videoQuality: String = "high",
    @SerializedName("audioQuality") val audioQuality: String = "high",
    @SerializedName("networkType") val networkType: String = "wifi",
    @SerializedName("bandwidth") val bandwidth: String = "1000",
    @SerializedName("latency") val latency: String = "50",
    @SerializedName("isEncrypted") val isEncrypted: Boolean = true,
    @SerializedName("encryptionType") val encryptionType: String = "DTLS",
    @SerializedName("iceServers") val iceServers: String = "[{\"urls\":\"stun:stun.l.google.com:19302\"}]",
    @SerializedName("iceTransportPolicy") val iceTransportPolicy: String = "all",
    @SerializedName("bundlePolicy") val bundlePolicy: String = "max-bundle",
    @SerializedName("rtcpMuxPolicy") val rtcpMuxPolicy: String = "require",
    @SerializedName("videoConstraints") val videoConstraints: String = "{\"width\":{\"ideal\":1280},\"height\":{\"ideal\":720},\"frameRate\":{\"ideal\":30}}",
    @SerializedName("audioConstraints") val audioConstraints: String = "{\"sampleRate\":{\"ideal\":48000},\"channelCount\":{\"ideal\":2}}"
)

// WebRTC ICE Candidate Request
data class WebRTCIceCandidateRequest(
    @SerializedName("sessionId") val sessionId: String,
    @SerializedName("candidate") val candidate: String,
    @SerializedName("sdpMid") val sdpMid: String,
    @SerializedName("sdpMLineIndex") val sdpMLineIndex: Int,
    @SerializedName("usernameFragment") val usernameFragment: String? = null,
    @SerializedName("foundation") val foundation: String? = null,
    @SerializedName("component") val component: String = "RTP",
    @SerializedName("protocol") val protocol: String = "UDP",
    @SerializedName("priority") val priority: String? = null,
    @SerializedName("ip") val ip: String? = null,
    @SerializedName("port") val port: Int? = null,
    @SerializedName("type") val type: String = "host",
    @SerializedName("networkType") val networkType: String = "wifi",
    @SerializedName("networkCost") val networkCost: String = "low",
    @SerializedName("addressFamily") val addressFamily: String = "IPv4",
    @SerializedName("bandwidth") val bandwidth: String? = null,
    @SerializedName("latency") val latency: String? = null,
    @SerializedName("packetLoss") val packetLoss: String? = null,
    @SerializedName("jitter") val jitter: String? = null,
    @SerializedName("isEncrypted") val isEncrypted: Boolean = true,
    @SerializedName("encryptionType") val encryptionType: String = "DTLS",
    @SerializedName("certificate") val certificate: String? = null
) 